### ISSUE TITLE
SyntaxError: Unexpected token )

### ISSUE THREAD

**Issue by appjitsu** [Shopify/shopify-express#105]
I'm trying to deploy my project to aws beanstalk with node v8.9.1.

```
> shopify-node-app@0.0.0 start /var/app/current
> nodemon ./bin/www

[33m[nodemon] 1.17.1[39m
[33m[nodemon] to restart at any time, enter `rs`[39m
[33m[nodemon] watching: *.*[39m
[32m[nodemon] starting `node ./bin/www.js`[39m
/var/app/current/node_modules/@shopify/shopify-express/routes/index.js:19
  );
  ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/app/current/node_modules/@shopify/shopify-express/index.js:2:22)
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
```

**Comment by phillipmalboeuf** [comment]
I'm getting the same error with Google cloud functions. Do we know what's going on?
