### ISSUE TITLE
ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by N0ps32** [Shopify/shopify-express#44]
During the oAuth process an error occurs because you are using "fetch" but not importing it before you're using it.

Platform info:
```
ts-node v4.0.2
node v9.5.0
typescript v2.7.1
```

I'm using the latest npm release.

```
ReferenceError: fetch is not defined
    at router.get (/home/benni/myproject/node_modules/@shopify/shopify-express/routes/shopifyAuth.js:72:5)
    at Layer.handle [as handle_request] (/home/benni/myproject/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/benni/myproject/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/benni/myproject/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/benni/myproject/node_modules/express/lib/router/layer.js:95:5)
    at /home/benni/myproject/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/benni/myproject/node_modules/express/lib/router/index.js:335:12)
    at next (/home/benni/myproject/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/benni/myproject/node_modules/express/lib/router/index.js:174:3)
    at router (/home/benni/myproject/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/benni/myproject/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/benni/myproject/node_modules/express/lib/router/index.js:317:13)
    at /home/benni/myproject/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/benni/myproject/node_modules/express/lib/router/index.js:335:12)
    at next (/home/benni/myproject/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/benni/myproject/node_modules/express/lib/router/index.js:174:3)
```

I fixed it locally by doing this:
```
global.fetch = require('node-fetch');
```

But that is obviously a terrible solution.

**Comment by py4object** [comment]
+1

**Comment by theptrk** [comment]
PR: https://github.com/Shopify/shopify-express/pull/47
