### ISSUE TITLE
shopify-express oAuth process breaks when sessions are not configured in express

### ISSUE THREAD

**Issue by N0ps32** [Shopify/shopify-express#45]
```
🔴 Error storing shop access token TypeError: Cannot set property 'accessToken' of undefined
    at shopStore.storeShop (/home/benni/myproject/node_modules/@shopify/shopify-express/routes/shopifyAuth.js:89:39)
    at ShopStoreTypeOrmService.<anonymous> (/home/benni/myproject/src/shop/services/shop-store-type-orm.service.ts:49:13)
    at Generator.next (<anonymous>)
    at fulfilled (/home/benni/myproject/src/shop/services/shop-store-type-orm.service.ts:16:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:18153) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'accessToken' of undefined
    at shopStore.storeShop (/home/benni/myproject/node_modules/@shopify/shopify-express/routes/shopifyAuth.js:89:39)
    at ShopStoreTypeOrmService.<anonymous> (/home/benni/myproject/src/shop/services/shop-store-type-orm.service.ts:51:13)
    at Generator.next (<anonymous>)
    at fulfilled (/home/benni/myproject/src/shop/services/shop-store-type-orm.service.ts:16:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:18153) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18153) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I don't need or want session support in my app.

The problem is that in shopifyAuth.js in the function that handles "/callback" doesn't actually check if a session is available and just blindly tries to save stuff into the session.

```
request.session.accessToken = accessToken;
request.session.shop = shop;
```

**Comment by theptrk** [comment]
Noob here. What do you mean "doesnt actually check if a session is available". What code would properly make all the checks to verify that?

**Comment by N0ps32** [comment]
```
if(request.session) {
    request.session.accessToken = accessToken;
    request.session.shop = shop;
}
```

Should solve the problem. But I've seen another branch on here where Shopify started work on fixing the Session problem. Maybe they need to have a session for some reason.

I've been running it without session support just fine for about 2 weeks now though.

**Comment by theptrk** [comment]
Interesting I thought we needed to keep this for all future calls. Are you storing the access token anywhere? Or does the application re authorize everyone?

**Comment by N0ps32** [comment]
All Access tokens are stored in the database using a custom TypeormStrategy. I'm not sure why they're trying to use sessions at all. They might be needed if you want to include a settings page into Shopify but I'm not yet at that stage in development where that is relevant.
