### ISSUE TITLE
Execution fails when I install this package.

### ISSUE THREAD

**Issue by kpatel1989** [Shopify/shopify-express#70]
/node_modules/@shopify/shopify-express/routes/index.js:19
  );
  ^
SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
....

The syntax error is because of the extra comma on the previous line. 
That is actually valid with new versions of javascript. I wonder why is this an error.

**Comment by jamiemtdwyer** [comment]
Thanks for following up! Glad you were able to get it sorted.
