### ISSUE TITLE
BadRequestError: request aborted // Shopify 499

### ISSUE THREAD

**Issue by BarryCarlyon** [Shopify/shopify-express#86]
Shopify Webhook into Nginx -> proxy_pass to nodeJS

> "POST /webhook/shop_update HTTP/1.1" 499 0 "-" "Ruby"

And catching the error:

```
{ BadRequestError: request aborted
    at IncomingMessage.onAborted (MYAPP/node_modules/raw-body/index.js:231:10)
    at IncomingMessage.emit (events.js:182:13)
    at abortIncoming (_http_server.js:444:9)
    at socketOnEnd (_http_server.js:460:5)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1090:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I believe this issue https://github.com/stream-utils/raw-body/issues/57 is the "problem"

Likely down to my globalisation of bodyParser.json in error

> app.use(bodyParser.json());

But probably worth to be able to support/handle `bodyParser.json`being globalised?

**Comment by janfabian** [comment]
👍 I confirm this issue

my current solution 

``` javascript
let json = require('body-parser').json();
json.unless = require('express-unless');
let middleware = [
    json.unless({ path: /\/webhooks*/ })
    / ....
]
```

**Comment by Mnabawy** [comment]
this issue is related to the body-parser package setup 

`
// parse application/json
app.use(bodyParser.json())

app.use(function (req, res) {
  res.setHeader('Content-Type', 'text/plain')
  res.write('you posted:\n')
  res.end(JSON.stringify(req.body, null, 2))
})
`

[adding a generic JSON and URL-encoded](https://github.com/expressjs/body-parser#expressconnect-top-level-generic)
