### ISSUE TITLE
SyntaxError: Unexpected token ) in /routes/index.js 

### ISSUE THREAD

**Issue by Dygerati** [Shopify/shopify-express#98]
I'm encountering this error when attempting to use this package in the context of a firebase cloud fuction, which refuses to deploy given a small syntax error: 

`Detailed stack trace: /user_code/node_modules/@shopify/shopify-express/routes/index.js:19
  );
  ^SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/node_modules/@shopify/shopify-express/index.js:2:22)
`

It appears to be due to a stray comma on the listed line, before the ending ')'. Looks like this:

`  router.use(
    '/api',
    rawParser,
    verifyApiCall,
    shopifyApiProxy,
  );`

Easy fix.

**Comment by Dygerati** [comment]
On closer inspection it looks like this is intentional (as evidenced by Prettifier config), and just an incompatibility with Firebase. I've forked the repo and make the necessary modifications instead.
